Repository bianjieai/irita, pull requests merged in 2020-12, with the labels that each got.

#57 Add wasm docs
  docs/SDK/Go_SDK/API/README.md
  docs/SDK/Go_SDK/API/wasm.md
  docs/console/modules/wasm.md
  docs/core_modules/README.md
  docs/core_modules/wasm.md
  docs/quick_start/README.md
  docs/quick_start/wasm.md
Labels: automerge, documentation

#58 Update dependency
  go.mod
  go.sum
Labels: automerge, bug

#59 Add gitattributes
  .gitattributes
Labels: automerge, build

#60 Add wasm flag for start cmd
  app/app.go
  cmd/irita/cmd/root.go
Labels: automerge

#61 Update dependency
  go.mod
  go.sum
Labels: automerge, build

#62 Modify deployment doc
  docs/installation/deployment.md
Labels: automerge, documentation

#63 Fix docker build
  Dockerfile
Labels: automerge, bug

#64 Update local testnet command
  Makefile
Labels: automerge, build

#66 Export seed in the deployment script
  docs/installation/deployment.md
Labels: automerge, build

#67 Add wasm swagger
  go.mod
  go.sum
  lite/config.json
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  proto/genutil/genesis.proto
  scripts/protoc-swagger-gen.sh
Labels: API, automerge, documentation

#72 Update grpc version
  go.mod
  go.sum
Labels: automerge, build

#74 Optimize deployment script
  docs/installation/deployment.md
  lite/swagger-ui/swagger.yaml
Labels: automerge

#78 Fix query issue_token_base_fee display bug
  cmd/irita/cmd/utils.go
Labels: automerge, bug

#77 Update wasm to fix contract instantiation rest
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  lite/swagger_legacy.yaml
Labels: automerge
