Repository bianjieai/irita, pull requests merged in 2020-11, with the labels that each got.

#43 Add unit test workflow
  .github/workflows/TestUnit.yml
  .github/workflows/automerge.yml
Labels: automerge

#44 Fix automerge config
  .github/workflows/automerge.yml
Labels: automerge

#45 Fix docker build
  Dockerfile
  Makefile
  docker-compose.yml
Labels: automerge, build

#46 Cleanup dependency
  app/app.go
  go.mod
  go.sum
  simapp/app.go
Labels: automerge, dependencies

#49 Use iritamod genutil and fix validator generation
  app/app.go
  cmd/irita/cmd/genrootcert.go
  cmd/irita/cmd/genvalidators.go
  cmd/irita/cmd/root.go
  cmd/irita/cmd/testnet.go
  go.mod
  go.sum
  modules/genutil/alias.go
  modules/genutil/client/cli/genkey.go
  modules/genutil/client/cli/init.go
  modules/genutil/client/cli/init_test.go
  modules/genutil/client/cli/validate_genesis.go
  modules/genutil/client/rest/query.go
  modules/genutil/collect.go
  modules/genutil/doc.go
  modules/genutil/genesis.go
  modules/genutil/genkey.go
  modules/genutil/gentx.go
  modules/genutil/gentx_test.go
  modules/genutil/module.go
  modules/genutil/types/codec.go
  modules/genutil/types/expected_keepers.go
  modules/genutil/types/genesis.pb.go
  modules/genutil/types/genesis_state.go
  modules/genutil/types/genesis_state_test.go
  modules/genutil/types/types.go
  modules/genutil/utils.go
  modules/genutil/utils_test.go
  simapp/app.go
  utils/ca/cert.go
  utils/ca/sm2_cert.go
  utils/ca/x509_cert.go
  utils/opensslcmd.go
Labels: automerge, bug, enhancement

#48 Add node module
  app/ante.go
  app/app.go
  cmd/irita/cmd/root.go
  go.mod
  go.sum
  simapp/app.go
Labels: automerge, enhancement

#50 Change validator to node
  app/ante.go
  app/app.go
  app/app_test.go
  app/export.go
  cmd/irita/cmd/genrootcert.go
  cmd/irita/cmd/genvalidators.go
  cmd/irita/cmd/root.go
  cmd/irita/cmd/testnet.go
  go.mod
  go.sum
  lite/config.json
  lite/swagger_legacy.yaml
  scripts/protoc-swagger-gen.sh
  simapp/app.go
  simapp/export.go
  simapp/test_helpers.go
Labels: automerge, enhancement

#52 Update iritamod version
  go.mod
  go.sum
Labels: automerge, build

#55 Update dependency
  go.mod
  go.sum
Labels: automerge, build
