Repository bianjieai/irita, pull requests merged in 2020-04, with the labels that each got.

#20 R4R: Use irismod modules
  Makefile
  app/app.go
  cli_test/record_test.go
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/index.html
  lite/swagger-ui/oauth2-redirect.html
  lite/swagger-ui/swagger-ui-bundle.js
  lite/swagger-ui/swagger-ui-standalone-preset.js
  lite/swagger-ui/swagger.yaml
  modules/record/alias.go
  modules/record/client/cli/flags.go
  modules/record/client/cli/query.go
  modules/record/client/cli/tx.go
  modules/record/client/rest/query.go
  modules/record/client/rest/rest.go
  modules/record/client/rest/tx.go
  modules/record/genesis.go
  modules/record/handler.go
  modules/record/internal/keeper/keeper.go
  modules/record/internal/keeper/keeper_test.go
  modules/record/internal/keeper/querier.go
  modules/record/internal/types/codec.go
  modules/record/internal/types/erros.go
  modules/record/internal/types/event.go
  modules/record/internal/types/genesis.go
  modules/record/internal/types/keys.go
  modules/record/internal/types/msgs.go
  modules/record/internal/types/querier.go
  modules/record/internal/types/types.go
  modules/record/module.go
  simapp/app.go
Labels: build

#26 R4R: Clean up
  cli_test/guardian_test.go
  cli_test/service_test.go
  cli_test/test_helpers.go
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
Labels: bug, build

#27 R4R: Remove duplicate file
  docs/README.md
  docs/features/nft.md
  docs/installation.md
Labels: documentation

#28 R4R: Modify service feature doc
  docs/features/service-pricing.json
  docs/features/service-result.json
  docs/features/service.md
Labels: documentation

#30 R4R: Add token cli_test and update docs
  cli_test/test_helpers.go
  cli_test/token_test.go
  docs/README.md
  docs/cli-client/bank.md
  docs/cli-client/intro.md
  docs/cli-client/nft.md
  docs/cli-client/record.md
  docs/cli-client/service.md
  docs/cli-client/token.md
  docs/features/service.md
  docs/features/token.md
  docs/light-client/intro.md
  docs/pics/chap2-1.jpg
  docs/pics/flow.jpg
  docs/pics/iris.jpg
  docs/pics/irita.jpg
  docs/pics/states.png
  go.sum
Labels: token

#31 R4R: Fix docker build
  Dockerfile
  Makefile
Labels: build
