Repository bianjieai/irita, pull requests merged in 2021-04, with the labels that each got.

#99 Update dependencies
  app/app.go
  go.mod
  go.sum
  simapp/app.go
Labels: automerge, dependencies

#100 Update admin.md
  docs/console/admin/perm.md
Labels: automerge

#102 Init point amount
  docs/installation/deployment.md
Labels: documentation

#105 Modify cmd testnet
  cmd/irita/cmd/testnet.go
Labels: build

#108 Modify denom in issue token base fee to point
  cmd/irita/cmd/testnet.go
Labels: automerge, build

#109 Release v2.0.0
  CHANGELOG.md
  app/app_test.go
  cmd/irita/cmd/genaccounts.go
  cmd/irita/cmd/testnet.go
  lite/config.json
  lite/cosmos_swagger_legacy.yaml
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  lite/swagger_legacy.yaml
  scripts/protoc-swagger-gen.sh
Labels: release

#110 Update changelog
  CHANGELOG.md
Labels: automerge, release
