Repository bianjieai/irita, pull requests merged in 2021-01, with the labels that each got.

#81 Docker: update go version
  Dockerfile
Labels: automerge, build

#83 Update wasmd version
  go.mod
  go.sum
Labels: build

#84 Update swagger docs
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  lite/swagger_legacy.yaml
  scripts/protoc-swagger-gen.sh
Labels: automerge

#85 Update cosmos-sdk to v0.40.0
  Makefile
  app/ante.go
  app/app.go
  cmd/irita/main.go
  go.mod
  go.sum
  scripts/protoc-swagger-gen.sh
  simapp/app.go
  simapp/test_helpers.go
Labels: automerge, dependencies

#86 Update swagger docs
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  lite/swagger_legacy.yaml
Labels: automerge, documentation
